import type { Metadata } from "next";
import "./globals.css";
import { IngestionProvider } from "@/lib/context/IngestionContext";
import { ThemeProvider } from "@/components/theme-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={` antialiased`}
      >
        <IngestionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
          
          </IngestionProvider>
      </body>
    </html>
  );
}
